
USE `PerscriptionDatabase`;

--
-- Table structure for table `Medications`
--

DROP TABLE IF EXISTS `Medications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `Medications` (
  `MedicationID` int(11) NOT NULL AUTO_INCREMENT
  `MedicationName` varchar(100) NOT NULL
  `GenericName` varchar(100) DEFAULT NULL
  PRIMARY KEY (`MedicationID`)
) ENGINE=InnoDB AUTO_INCREMENT=608 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Medications`
--

LOCK TABLES `Medications` WRITE;
/*!40000 ALTER TABLE `Medications` DISABLE KEYS */;
INSERT INTO `Medications` VALUES
('Suboxone''Buprenorphine/Naloxone'),
('Carisoprodol''Carisoprodol'),
('Celebrex''Celecoxib'),
('Tylenol with Codeine''Codeine'),
('Cyclobenzaprine''Cyclobenzaprine'),
('Diclofenac sodium SR''Diclofenac'),
('Fentanyl transdermal''Fentanyl Transdermal'),
('Hydrocodone/APAP''Hydrocodone'),
('Ibuprofen''Ibuprofen'),
('Indomethacin''Indomethacin'),
('Lidoderm','Lidocaine'),
('Meloxicam','Meloxicam'),
('Methadone HCl non-inj','Methadone'),
('Methocarbamol','Methocarbamol'),
('Morphine sulfate ER','Morphine'),
('Naproxen','Naproxen'),
('OxyContin','Oxycodone'),
('Elmiron','Pentosan'),
('Sumatriptan oral','Sumatriptan'),
('Tramadol','Tramadol'),
('Acyclovir','Acyclovir'),
('Albenza','Albendazole'),
('Amoxicillin','Amoxicillin'),
('Amoxicillin/pot. clav','Amoxicillin/Clavulanate'),
('Reyataz','Atazanavir'),
('Azithromycin','Azithromycin'),
('Cefdinir','Cefdinir'),
('Cefuroxime axetil','Cefuroxime'),
('Cephalexin','Cephalexin'),
('Chlorhexidine gluconate','Chlorhexidine'),
('Ciprofloxacin HCl','Ciprofloxacin Oral'),
('Ciprodex Otic','Ciprofloxacin Otic'),
('Clarithromycin','Clarithromycin'),
('Clindamycin systemic','Clindamycin Systemic'),
('Clindamycin topical','Clindamycin Topical'),
('In Various Combinations','Diphtheria'),
('Doxycycline','Doxycycline'),
('Sustiva','Efavirenz'),
('Truvada','Emtricitabine/Tenofovir'),
('Baraclude','Entecavir'),
('Dificid','Fidaxomicin'),
('Fluconazole','Fluconazole'),
('Zymar','Gatifloxacin Ophthalmic'),
('Pedvax HIB','Haemophilus Influenzae Type B'),
('Havrix','Hepatitis A'),
('Recombivax HB; Engerix-B','Hepatitis B'),
('Gardasil','Human Papillomavirus'),
('Hydroxychloroquine','Hydroxychloroquine'),
('Imiquimod','Imiquimod'),
('Fluzone','Influenza Inactivated'),
('Flumist','Influenza Live'),
('Ketoconazole topical','Ketoconazole Topical'),
('Levaquin','Levofloxacin'),
('Selzentry','Maraviroc'),
('MMR','Measles, Mumps and Rubella'),
('Menactra, Menomune','Meningococcal (Conjugate and Polysaccharide)'),
('Metronidazole tabs','Metronidazole'),
('Minocycline','Minocycline'),
('Avelox','Moxifloxacin'),
('Vigamox','Moxifloxacin Ophthalmic'),
('Mupirocin','Mupirocin'),
('Alinia','Nitazoxanide'),
('Nitrofurantoin mono mcr','Nitrofurantoin'),
('Nystatin systemic','Nystatin Systemic'),
('Nystatin topical','Nystatin Topical'),
('Tamiflu','Oseltamivir'),
('Penicillin VK','Penicillin'),
('In Various Combinations','Pertussis'),
('Prevnar 13, Pneumovax 23','Pneumococcal (Conjugate and Polysaccharide)'),
('IPOL','Polio'),
('Insentress','Raltegravir'),
('RotaTeq','Rotavirus'),
('Terbinafine HCl','Terbinafine'),
('In Various Combinations','Tetanus'),
('Trimethoprim/sulfa','Trimethoprim/Sulfamethoxazole'),
('Valtrex','Valacyclovir'),
('Varivax','Varicella'),
('Zostavax','Zoster'),
('Amlodipine besylate','Amlodipine'),
('Atenolol','Atenolol'),
('Lipitor','Atorvastatin'),
('Benazepril','Benazepril'),
('Zebeta','Bisoprolol'),
('Atacand','Candesartan'),
('Carvedilol','Carvedilol'),
('Hygroton','Chlorthalidone'),
('Clonidine','Clonidine'),
('Plavix','Clopidogrel'),
('Welchol','Colesevelam'),
('Pradaxa','Dabigatran'),
('Digoxin','Digoxin'),
('Diltiazem','Diltiazem'),
('Persantine','Dipyridamole'),
('Doxazosin','Doxazosin'),
('Enalapril','Enalapril'),
('Lovenox','Enoxaparin'),
('Zetia','Ezetimibe'),
('Felodipine ER','Felodipine'),
('Fenofibrate','Fenofibrate'),
('Fosinopril sodium','Fosinopril'),
('Furosemide oral','Furosemide'),
('Gemfibrozil','Gemfibrozil'),
('Hydralazine','Hydralazine'),
('Hydrochlorothiazide','Hydrochlorothiazide'),
('Avapro','Irbesartan'),
('Isosorbide mononitrate','Isosorbide Mononitrate'),
('Labetalol','Labetalol'),
('Lisinopril','Lisinopril'),
('Cozaar','Losartan'),
('Lovastatin','Lovastatin'),
('Metoprolol succinate','Metoprolol'),
('Bystolic','Nebivolol'),
('Niaspan','Niacin'),
('Nifedipine ER','Nifedipine'),
('Nitroglycerin','Nitroglycerin'),
('Benicar','Olmesartan'),
('Lovaza','Omega-3-Ethyl Esters'),
('Effient','Prasugrel'),
('Pravastatin','Pravastatin'),
('Propranolol HCl','Propranolol'),
('Quinapril','Quinapril'),
('Ramipril','Ramipril'),
('Ranexa','Ranolazine'),
('Xarelto','Rivaroxaban'),
('Crestor','Rosuvistatin'),
('Simvastatin','Simvastatin'),
('Spironolactone','Spironolactone'),
('Terazosin','Terazosin'),
('Samsca','Tolvaptan'),
('Triamterene w/HCTZ','Triamterene/Hydrochlorothiazide'),
('Diovan','Valsartan'),
('Verapamil SR','Verapamil'),
('Warfarin','Warfarin'),
('Alendronate','Alendronate'),
('Premarin tabs','Conjugated Estrogen'),
('Cyanocobalamin','Cyanocobalamin'),
('Dexamethasone oral','Dexamethasone'),
('Estradiol oral','Estradiol Oral'),
('Vivelle-DOT','Estradiol Transdermal Patch'),
('Nuvaring','Ethinyl Estradiol/Etonogestrel Ring'),
('Byetta','Exenatide'),
('Folic acid','Folic Acid'),
('Glimepiride','Glimepiride'),
('Glipizide','Glipizide'),
('Boniva','Ibandronate'),
('Humulin N','Insulin'),
('NovoLog','Insulin Aspart'),
('Levemir','Insulin Detemir'),
('Lantus','Insulin Glargine'),
('Humalog','Insulin Lispro'),
('Levothyroxine','Levothyroxine'),
('Tradjenta','Linagliptin'),
('Victoza','Liraglutide'),
('Medroxyprogesterone tab','Medroxyprogesterone Oral'),
('Metformin','Metformin'),
('Methylprednisolone tabs','Methylprednisolone Oral'),
('Oral Contraceptive','Oral Contraceptive - Biphasic'),
('Oral Contraceptive','Oral Contraceptive - Monophasic'),
('Oral Contraceptive','Oral Contraceptive - Triphasic'),
('Actos','Pioglitazone'),
('Klor-Con','Potassium Chloride'),
('SSKI','Potassium Iodide'),
('Prednisolone sd phs oral','Prednisolone Oral'),
('Prednisone oral','Prednisone'),
('Prenatal 1+1','Prenatal 1+1'),
('Prometrium','Progesterone'),
('Evista','Raloxifene'),
('Prandin','Repaglinide'),
('Actonel','Risedronate'),
('Avandia','Rosiglitazone'),
('Onglyza','Saxagliptin'),
('Januvia','Sitagliptin'),
('AndroGel','Testosterone'),
('Thyroid, Armour','Thyroid'),
('Enablex','Darifenacin'),
('Dexilant','Dexlansoprazole'),
('Diphenoxylate w/atropine','Diphenoxylate/Atropine'),
('Nexium','Esomeprazole'),
('Famotidine','Famotidine'),
('Finasteride','Finasteride'),
('Prevacid','Lansoprazole'),
('Amitiza','Lubiprostone'),
('Metoclopramide','Metoclopramide'),
('Omeprazole','Omeprazole'),
('Ondansetron','Ondansetron'),
('Pantoprazole','Pantoprazole'),
('Phenazopyridine HCl','Phenazopyridine'),
('Polyethylene glycol','Polyethylene Glycol'),
('Aciphex','Rabeprazole'),
('Ranitidine HCl','Ranitidine'),
('Flomax','Tamsulosin'),
('Detrol LA','Tolterodine'),
('Differin','Adapalene'),
('Allopurinol','Allopurinol'),
('Arimidex','Anastrozole'),
('Lumigan','Bimatoprost Ophthalmic'),
('Alphagan P','Brimonidine'),
('Clobetasol','Clobetasol'),
('Clotrimazole/betameth.','Clotrimazole/Betamethasone'),
('Colchicine','Colchicine'),
('Restasis','Cyclosporine Ophthalmic'),
('Aranesp','Darbepoetin'),
('Epipen','Epinephrine'),
('Procrit','Epoetin Alfa'),
('Fluocinonide','Fluocinonide'),
('Uloric','Fubuxostat'),
('Hydrocortisone top Rx','Hydrocortisone Topical'),
('Xalatan','Latanoprost'),
('Lotemax','Loteprednol Ophthalmic'),
('Methotrexate','Methotrexate'),
('Viagra','Sildenafil'),
('Tacrolimus','Tacrolimus'),
('Cialis','Tadalafil'),
('Travatan Z','Travoprost'),
('Triamcinolone acet top','Triamcinolone Topical'),
('Levitra','Vardenafil'),
('Tizanidine HCl','Tizanidine'),
('Alprazolam','Alprazolam'),
('Amitriptyline','Amitriptyline'),
('Abilify','Aripiprazole'),
('Strattera','Atomoxetine'),
('Baclofen','Baclofen'),
('Benzonatate','Benzonatate'),
('Benztropine','Benztropine'),
('Bupropion ER','Bupropion'),
('Buspirone HCl','Buspirone'),
('Carbamazepine','Carbamazepine'),
('Carbidopa/levodopa','Carbidopa/Levodopa'),
('Citalopram HBR','Citalopram'),
('Onfi','Clobazam'),
('Clonazepam','Clonazepam'),
('Pristiq','Desvenlafaxine'),
('Focalin XR','Dexmethylphenidate'),
('Diazepam','Diazepam'),
('Dicyclomine HCl','Dicyclomine'),
('Divalproex sodium','Divalproex'),
('Aricept','Donepezil'),
('Doxepin','Doxepin'),
('Cymbalta','Duloxetine'),
('Avodart','Dutasteride'),
('Relpax','Eletriptan'),
('Lexapro','Escitalopram'),
('Lunesta','Eszopiclone'),
('Fluoxetine','Fluoxetine'),
('Gabapentin','Gabapentin'),
('Vimpat','Lacosamide'),
('Lamotrigine','Lamotrigine'),
('Levetiracetam','Levetiracetam'),
('Vyvanse','Lisdexamfetamine'),
('Lithium carbonate','Lithium carbonate'),
('Lorazepam','Lorazepam'),
('Meclizine HCl','Meclizine'),
('Namenda','Memantine'),
('Skelaxin','Metaxalone'),
('Methylphenidate','Methylphenidate'),
('Mirtazapine','Mirtazapine'),
('Provigil','Modafinil'),
('Nortriptyline','Nortriptyline'),
('Zyprexa','Olanzapine'),
('Oxcarbazepine','Oxcarbazepine'),
('Oxybutynin chloride','Oxybutynin'),
('Paroxetine','Paroxetine'),
('Phenobarbital','Phenobarbital'),
('Phentermine','Phentermine'),
('Phenytoin sodium ext','Phenytoin'),
('Mirapex','Pramipexole'),
('Lyrica','Pregabalin'),
('Prochlorperazine maleate','Prochlorperazine'),
('Promethazine tabs','Promethazine'),
('Seroquel','Quetiapine'),
('Risperidone','Risperidone'),
('Ropinirole HCl','Ropinirole'),
('Sertraline','Sertraline'),
('Vesicare','Solifenacin'),
('Temazepam','Temazepam'),
('Topiramate','Topiramate'),
('Trazodone HCl','Trazodone'),
('Chantix','Varenicline'),
('Venlafaxine','Venlafaxine'),
('Viibryd','Vilazodone'),
('Geodon Oral','Ziprasidone'),
('Zolpidem tartrate','Zolpidem'),
('ProAir HFA','Albuterol'),
('Astelin','Azelastine'),
('Pulmicort Respules','Budesonide'),
('Symbicort','Budesonide/Formoterol'),
('Cetirizine','Cetirizine'),
('Fexofenadine','Fexofenadine'),
('Fluticasone nasal','Fluticasone Nasal'),
('Flovent HFA','Fluticasone Oral'),
('Advair Diskus','Fluticasone/Salmeterol'),
('Hydroxyzine','Hydroxyzine'),
('Combivent','Ipratropium/Albuterol'),
('Xopenex HFA','Levalbuterol'),
('Xyzal','Levocetirizine'),
('Nasonex','Mometasone'),
('Singulair','Montelukast'),
('Patanol','Olopatadine'),
('Spiriva','Tiotropium'),
('Nasacort AQ','Triamcinolone Nasal'),
('Adderall XR','Amphetimine Salt HCL'),
('Flagyl, Flagyl ER','Metronidazole'),
('Diflucan','Fluconazole'),
('Nizoral','Ketoconazole'),
('Mycostatin, Nystop','Nystatin'),
('Lamisil','Terbinafine'),
('Zovirax','Acyclovir'),
('Valtrex','Valacyclovir'),
('Keflex','Cephalexin'),
('Ceftin','Cefuroxime axetil'),
('Omnicef','Cefdinir'),
('Cipro (XR)','Ciprofloxacin'),
('Levaquin','Levofloxacin'),
('Avelox','Moxifloxacin'),
('Zithromax, Zmax,Azasite','Azithromycin'),
('Biaxin (XL)','Clarithromycin'),
('Cleocin, Cleocin T,Evoclin, Clindagel','Clindamycin'),
('Macrobid, Macrodantin,Furadantin','Nitrofurantoin'),
('Amoxil','Amoxicillin'),
('Augmentin, AugmentinXR','Amoxicillin + Clavulanate'),
('Veetids, Pen-Vee K','Penicillin V Potassium'),
('Bactrim, Bactrim DS,Septra, Septra DS','Sulfamethoxazole +Trimethoprim'),
('Vibramycin, Doryx,Adoxa, Monodox,Oracea, Periostat','Doxycycline'),
('Metrogel, MetrogelVaginal, Metrocream,Metrolotion','Metronidazole'),
('Bactroban','Mupirocin'),
('Mycolog II','Nystatin + Triamcinolone'),
('Peridex, PerioGard','Chlorhexidine Gluconate'),
('Tamiflu','Olsetamivir'),
('Truvada','Emtricitabine + Tenofovir'),
('Combivir','Zidovudine + Lamivudine'),
('Vasotec','Enalapril'),
('Altace','Ramipril'),
('Accupril, Accuretic','Quinapril'),
('Lotensin, Lotensin HCT','Benazepril, Ben/HCTZ'),
('Zestril or Prinivil,Zestoretic','Lisinopril, Lis/HCTZ'),
('Cardura, Cardura XL','Doxazosin Mesylate'),
('Hytrin','Terazosin'),
('Catapres, CatapresTTS, Nexiclon XR,Kapvay ER','Clonidine'),
('Cordarone','Amiodarone'),
('Coumadin','Warfarin Sodium'),
('TRICOR, Trilipix','Fenofibrate'),
('Lopid','Gemfibrozil'),
('Niaspan ER','Niacin'),
('Lipitor','Atorvastatin'),
('Mevacor, Altoprev ER','Lovastatin'),
('Pravachol','Pravastatin'),
('Crestor','Rosuvastatin'),
('Vytorin','Simvastatin/ezetimibe'),
('3 Zocor','Simvastatin'),
(') Ecotrin','Aspirin'),
('Exforge, Exforge HCT','Amlodipine + Valsartan'),
('Diovan, Diovan HCT','Valsartan, Val/HCTZ'),
('Avapro, Avalide','Irbesartan,Irbesartan/HCTZ'),
('Atacand, Atacand HCT','Candesartan, Can/HCTZ'),
('Benicar, Benicar HCT','Olmesartan'),
('Cozaar, Hyzaar','Losartan, Los/HCTZ'),
('Tenormin','Atenolol'),
('Toprol XL','Metoprolol Succinate'),
('Lopressor','Metoprolol Tartrate'),
('Zebeta, Ziac','Bisoprolol, Bisoprolol +HCTZ'),
('Tenoretic','Atenolol/chlorthalidone'),
('Inderal, Inderal LA,Innopran, Innopran XL','Propranolol'),
('Normodyne or Trandate','Labetalol'),
('Lanoxin or Lanoxicap','Digoxin'),
('Azor, Tribenzor','Amlodipine + Olmestartan'),
('Norvasc','Amlodipine'),
('Procardia, ProcardiaXL, Adalat CC','Nifedipine'),
('Lotrel','Amlodipine + Benazepril'),
('Caduet','Amlodipine + Atorvastatin'),
('Pradaxa','Dabigatran'),
('Klor-Con','Potassium Chloride'),
('Eliquis','Apixaban'),
('Lasix','Furosemide'),
('Lovenox','Enoxaparin'),
('Imdur, ISMO','Isosorbide Mononitrate'),
('Nitrostat','Nitroglycerin SL'),
('Nitro-Dur','Topical Nitroglycerin'),
('Cardizem, CardizemSR, Cardizem CD,Cardizem LA, Tiazac','Diltiazem'),
('Plavix','Clopidogrel'),
('Dyazide capsules orMaxzide tablets','Triamterene + HCTZ'),
('Aldactone, Aldactazide','Spironolactone, Spir/HCTZ'),
('Lozol','Indapamide'),
('Thalidone, Hygroton','Chlorthalidone'),
('','Hydrochlorothiazide (akaHCTZ)'),
('Zofran, Zofran ODT','Ondansetron'),
('Aricept','Donepezil'),
('Exelon, Exelon Patch','Rivastigmine'),
('Fiorinal, Fiorinal withcodeine','Butalbital + aspirin +caffeine, available with orwithout codeine'),
('Fioricet, Fioricet withcodeine','Butalbital + acetaminophen+ caffeine (sometimescalled B-A-C), availablewith or without'),
('Buspar','Buspirone'),
('Transderm-Scop','Scopolamine'),
('Remeron','Mirtazapine'),
('Desyrel','Trazodone'),
('Tegretol (XR)','Carbamazepine'),
('Lamictal','Lamotrigine'),
('Keppra','Levetiracetam'),
('Trileptal','Oxcarbazepine'),
('Dilantin Kapseals','Phenytoin Sodium'),
('Depakote (ER)','Divalproex'),
('Phenobarbital','Phenobarbital'),
('Topamax','Topiramate'),
('Neurontin','Gabapentin'),
('Atarax','Hydroxyzine hydrochloride'),
('Relpax','Eletriptan'),
('Maxalt, Maxalt MLT','Rizatriptan'),
('Imitrex','Sumatriptan'),
('Cogentin','Benztropine'),
('Sinemet (CR)','Levodopa/Carbidopa'),
('Mirapex','Pramipexole'),
('Requip','Ropinirole'),
('Zyprexa','Olanzapine'),
('Seroquel (XR)','Quetiapine'),
('Risperdal','Risperidone'),
('Geodon','Ziprasidone'),
('Abilify','Aripiprazole'),
('Antivert','Meclizine'),
('Xanax (XR)','Alprazolam'),
('Klonopin','Clonazepam'),
('Valium','Diazepam'),
('Ativan','Lorazepam'),
('Restoril','Temazepam'),
('Adipex-P','Phentermine'),
('Concerta or Ritalin (ER)or Metadate CD','Methylphenidate'),
('Strattera','Atomoxetine'),
('Adderall (XR)','(Dex)/Amphetamine Mixedsalts'),
('Vyvanse','Lisdexamfetamine'),
('Provigil','Modafinil'),
('Focalin (XR)','Dexmethylphenidate'),
('Sonata','Zaleplon'),
('Flexeril','Cyclobenzaprine'),
('Skelaxin','Metaxalone'),
('Soma','Carisoprodol'),
('Duragesic','Fentanyl'),
('MS Contin','Morphine Sulfate'),
('Oxycontin','Oxycodone'),
('Percocet or Roxicet','Oxycodone/APAP'),
('Tylenol with Codeine','Acetaminophen/ Codeine'),
('Tussionex','Hydrocodone /chlorpheniramine Polistirex'),
('Vicoprofen','Hydrocodone/Ibuprofen'),
('Lortab or Vicodin orLorcet','Hydrocodone/APAP'),
('Lyrica','Pregabalin'),
('Chantix','Varenicline Tartrate'),
('Namenda','Memantine'),
('Voltaren, Cataflam','Enteric Diclofenac sodium,Diclofenac potassium (nonenteric coated formulation)'),
('Lodine (XL)','Etodolac'),
('Indocin','Indomethacin'),
('Toradol','Ketorolac Tromethamine'),
('Mobic','Meloxicam'),
('Relafen','Nabumetone'),
('Naprosyn,Anaprox/Aleve','Naproxen and Naproxensodium'),
('Feldene','Piroxicam'),
('Motrin or Advil','Ibuprofen'),
('Celebrex','Celecoxib'),
('Arthrotec','Diclofenac/Misoprostol'),
('Ultram, Ultram ER','Tramadol'),
('Ultracet','Tramadol + acetaminophen'),
('Tylenol','Acetaminophen'),
('Lunesta','Eszopiclone'),
('Ambien (CR)','Zolpidem'),
('Pristiq','Desvenlafaxine'),
('Cymbalta','Duloxetine'),
('Effexor (XR)','Venlafaxine'),
('Celexa','Citalopram'),
('Lexapro','Escitalopram'),
('Prozac or Sarafem','Fluoxetine'),
('Paxil (CR)','Paroxetine'),
('Zoloft','Sertraline'),
('Lidoderm Patches','Lidocaine'),
('Elavil','Amitriptyline'),
('Tofranil (PM)','Imipramine'),
('Eskalith or Lithobid','Lithium Carbonate'),
('Differin','Adapalene'),
('Benzaclin','Clindamycin/BenzoylPeroxide'),
('Benzamycin','Erythromycin/BenzoylPeroxide'),
('Clobex','Clobetasol'),
('Elocon','Mometasone'),
('Kenalog','Triamcinolone'),
('Elidel','Pimecrolimus'),
('Lotrisone','Clotrimazole/Betamethason e Diproprionate'),
('Lidex, Lidex-E, Vanos','Fluocinonide topical'),
('Propecia or Proscar','Finasteride'),
('Accutane or Claravis','isotretinoin'),
('AndroGel','Testosterone'),
('Glucophage (XR),Fortamet','Metformin'),
('Januvia, Janumet (XR)','Sitagliptin, Sit+Metformin'),
('Onglyza','Saxagliptin'),
('Amaryl','Glimepiride'),
('Glucotrol (XL)','Glipizide'),
('Micronase, Glucovance','Glyburide,Glyburide/Metformin'),
('Actos','Pioglitazone'),
('Byetta, Bydureon','Exenatide, Exenatide weekly'),
('Victoza','Liraglutide'),
('Fosamax','Alendronate'),
('Boniva','Ibandronate'),
('Actonel, Atelvia','Risedronate, delayed release enteric coated risedronate'),
('Estratest (HS)','Estrogen/Methyltestosteron e'),
('Combipatch','Estradiol/Norethindrone'),
('Premarin','Conjugated Estrogens'),
('Climara, Estrace','Estradiol'),
('Evista','Raloxifene'),
('Prempro or Premphase','Conjugated Estrogens with medroxyprogesterone'),
('Colcrys','Colchicine'),
('Zyloprim','Allopurinol'),
('Uloric','Febuxostat'),
('Provera','MedroxyprogesteroneAcetate'),
('Humulin R','Insulin - regular'),
('Humulin N','Insulin - NPH'),
('Levemir','Insulin Detemir'),
('Lantus','Insulin Glargine'),
('Novolog','Insulin Aspart'),
('Humalog','Insulin Lispro'),
('Apidra','Insulin Glulisine'),
('','Ethinyl Estradiol/Drospirenone'),
('Kariva, Ortho-Cept,Mircette, Desogen orApri','Ethinyl Estradiol /Desogestrel'),
('Aviane, Alesse','Ethinyl Estradiol /Levonorgestrel'),
('Loestrin FE','Norethindrone/EthinylEstradiol,Fe+'),
('TriNessa, Tri-Sprintec','Norgestimate & Ethinyl Estradiol'),
('Ortho Tri-Cyclen (Lo)','Norgestimate/EthinylEstradiol'),
('Ortho Evra','Ethinyl Estradiol /Norelgestromin'),
('Novolin 70/30, Humulin70/30','Insulin 70% NPH/ 30 %Regular'),
('Novalog Mix 70/30,Humalog Mix 75/25','Insulin 70% protamine/ 30 % rapid acting'),
('Depo-Provera','Medroxyprogesterone'),
('Deltasone','Prednisone'),
('Medrol','Methylprednisolone'),
('Armour thyroid','Desiccated thyroid'),
('Synthroid or Levoxyl','Levothyroxine'),
('Vivelle-Dot, Estraderm','Estradiol'),
('NuvaRing','Ethinyl Estradiol /Etonogestrel'),
('Vagifem','Estradiol'),
('Bentyl','Dicyclomine'),
('Levsin/Levbid/Levsinex','Hyoscyamine'),
('Imodium','Loperamide'),
('Lomotil','Diphenoxylate/Atropine'),
('Phenergan','Promethazine'),
('Amitiza',''),
('Xenical','Orlistat'),
('Pepcid','Famotidine'),
('Zantac','Ranitidine'),
('Miralax, Glycolax','Polyethylene Glycol'),
('Reglan','Metoclopramide'),
('Nexium','Esomeprazole'),
('Prevacid','Lansoprazole'),
('Prilosec','Omeprazole'),
('Protonix','Pantoprazole'),
('Aciphex','Rabeprazole'),
('Zegerid','Omeprazole/sodiumbicarbonate'),
('Avodart','Dutasteride'),
('Flomax','Tamsulosin'),
('Uroxatral','Alfuzosin'),
('Levitra','Vardenafil'),
('Viagra','Sildenafil'),
('Cialis','Tadalafil'),
('Ditropan (XL)','Oxybutynin'),
('Detrol (LA)','Tolterodine'),
('Enablex','Darifenacin'),
('Pyridium','Phenazopyridine'),
('Calcitriol','cholecalciferol'),
('Alphagan P','Brimonidine'),
('Xalatan','Latanaprost'),
('Timoptic (XE)','Timolol'),
('Travatan','Travoprost'),
('Combigan','Brimonidine/Timolol'),
('Pataday or Patanol','Olopatadine'),
('Tobradex','Tobramycin/Dexamethasone'),
('Vigamox','Moxifloxacin'),
('Restasis','Cyclosporine'),
('Cosopt','Dorzolamide/Timolol'),
('Zymar','Gatifloxacin'),
('Lumigan','Bimatoprost'),
('Cortisporin Otic','Neomycin/polymyxin/hydrocortisone'),
('Ciprodex, Cipro HC','Ciprofloxacin/Dexamethasone,Ciprofloxacin/Hydrocortisone'),
('Astelin','Azelastine'),
('Rhinocort Aqua','Budesonide Nasal Spray'),
('Flonase','Fluticasone'),
('Nasonex,','Mometasone'),
('Singulair','Montelukast'),
('Proair HFA or VentolinHFA or Proventil HFA','Albuterol'),
('Xopenex (HFA)','levalbuterol'),
('Pulmicort Respules,Flexhaler','Budesonide InhalationSuspension'),
('Flovent','Fluticasone'),
('Advair','Fluticasone/Salmeterol'),
('Respimat or Duoneb','Albuterol/Ipratropium'),
('Spiriva HandiHaler','Tiotropium'),
('Atrovent','Ipratropium Bromide'),
('Zyrtec','Cetirizine'),
('Clarinex','Desloratadine'),
('Claritin','Loratidine'),
('Allegra (D)','Fexofenadine (PSE)'),
('Mucinex (D, DM)','Guaifenesin'),
('Cheratussin AC','Guaifenesin & Codeine'),
('Zostavax','herpes zoster vaccine'),
('Gardasil, Cervarix','Human papillomavirus vaccine'),
('Afluria or Fluvirin or Fluzone','influenza virus vaccine'),
('Pneumovax','pneumococcal polysaccharide vaccine'),
('Tdap','Tetanus, Diphtheria,Pertussis Vaccine'),
('Dosage FormAbbreviationsXR or XL or ERXELASRCR','Extended releaseExtended effectLong Actingsustained releaseControlled release'),
('TTSODTDPMHS','Transdermal TherapeuticSystemOrally disintegrating tabDecongestanteveninghalf-s');
/*!40000 ALTER TABLE `Medications` ENABLE KEYS */;
UNLOCK TABLES;
