USE `PrescriptionDatabase`;

LOCK TABLES `Medications` WRITE;
/*!40000 ALTER TABLE `Medications` DISABLE KEYS */;
INSERT INTO `Medications` VALUES
(302,'Flagyl, Flagyl ER','Metronidazole'),
(303,'Diflucan','Fluconazole'),
(304,'Nizoral','Ketoconazole'),
(305,'Mycostatin, Nystop','Nystatin'),
(306,'Lamisil','Terbinafine'),
(307,'Zovirax','Acyclovir'),
(309,'Valtrex','Valacyclovir'),
(310,'Keflex','Cephalexin'),
(311,'Ceftin','Cefuroxime axetil'),
(312,'Omnicef','Cefdinir'),
(313,'Cipro (XR)','Ciprofloxacin'),
(314,'Levaquin','Levofloxacin'),
(315,'Avelox','Moxifloxacin'),
(316,'Zithromax, Zmax,<br>Azasite','Azithromycin'),
(317,'Biaxin (XL)','Clarithromycin'),
(318,'Cleocin, Cleocin T,<br>Evoclin, Clindagel','Clindamycin'),
(319,'Macrobid, Macrodantin,<br>Furadantin','Nitrofurantoin'),
(320,'Amoxil','Amoxicillin'),
(321,'Augmentin, Augmentin<br>XR','Amoxicillin + Clavulanate'),
(322,'Veetids, Pen-Vee K','Penicillin V Potassium'),
(323,'Bactrim, Bactrim DS,<br>Septra, Septra DS','Sulfamethoxazole +<br>Trimethoprim'),
(324,'Vibramycin, Doryx,<br>Adoxa, Monodox,<br>Oracea, Periostat','Doxycycline'),
(325,'Metrogel, Metrogel<br>Vaginal, Metrocream,<br>Metrolotion','Metronidazole'),
(326,'Bactroban','Mupirocin'),
(327,'Mycolog II','Nystatin + Triamcinolone'),
(328,'Peridex, PerioGard','Chlorhexidine Gluconate'),
(329,'Tamiflu','Olsetamivir'),
(330,'Truvada','Emtricitabine + Tenofovir'),
(331,'Combivir','Zidovudine + Lamivudine'),
(335,'Vasotec','Enalapril'),
(336,'Altace','Ramipril'),
(337,'Accupril, Accuretic','Quinapril'),
(338,'Lotensin, Lotensin HCT','Benazepril, Ben/HCTZ'),
(339,'Zestril or Prinivil,<br>Zestoretic','Lisinopril, Lis/HCTZ'),
(340,'Cardura, Cardura XL','Doxazosin Mesylate'),
(341,'Hytrin','Terazosin'),
(342,'Catapres, Catapres<br>TTS, Nexiclon XR,<br>Kapvay ER','Clonidine'),
(343,'Cordarone','Amiodarone'),
(344,'Coumadin','Warfarin Sodium'),
(345,'TRICOR, Trilipix','Fenofibrate'),
(346,'Lopid','Gemfibrozil'),
(347,'Niaspan ER','Niacin'),
(348,'Lipitor','Atorvastatin'),
(349,'Mevacor, Altoprev ER','Lovastatin'),
(350,'Pravachol','Pravastatin'),
(351,'Crestor','Rosuvastatin'),
(352,'Vytorin','Simvastatin/ezetimibe'),
(353,'3 Zocor','Simvastatin'),
(354,') Ecotrin','Aspirin'),
(355,'Exforge, Exforge HCT','Amlodipine + Valsartan'),
(356,'Diovan, Diovan HCT','Valsartan, Val/HCTZ'),
(357,'Avapro, Avalide','Irbesartan,<br>Irbesartan/HCTZ'),
(358,'Atacand, Atacand HCT','Candesartan, Can/HCTZ'),
(359,'Benicar, Benicar HCT','Olmesartan'),
(360,'Cozaar, Hyzaar','Losartan, Los/HCTZ'),
(361,'Tenormin','Atenolol'),
(362,'Toprol XL','Metoprolol Succinate'),
(363,'Lopressor','Metoprolol Tartrate'),
(364,'Zebeta, Ziac','Bisoprolol, Bisoprolol +<br>HCTZ'),
(365,'Tenoretic','Atenolol/chlorthalidone'),
(366,'Inderal, Inderal LA,<br>Innopran, Innopran XL','Propranolol'),
(368,'Normodyne or Trandate','Labetalol'),
(369,'Lanoxin or Lanoxicap','Digoxin'),
(370,'Azor, Tribenzor','Amlodipine + Olmestartan'),
(371,'Norvasc','Amlodipine'),
(372,'Procardia, Procardia<br>XL, Adalat CC','Nifedipine'),
(373,'Lotrel','Amlodipine + Benazepril'),
(374,'Caduet','Amlodipine + Atorvastatin'),
(375,'Pradaxa','Dabigatran'),
(376,'Klor-Con','Potassium Chloride'),
(378,'Eliquis','Apixaban'),
(379,'Lasix','Furosemide'),
(380,'Lovenox','Enoxaparin'),
(381,'Imdur, ISMO','Isosorbide Mononitrate'),
(382,'Nitrostat','Nitroglycerin SL'),
(383,'Nitro-Dur','Topical Nitroglycerin'),
(384,'Cardizem, Cardizem<br>SR, Cardizem CD,<br>Cardizem LA, Tiazac','Diltiazem'),
(386,'Plavix','Clopidogrel'),
(387,'Dyazide capsules or<br>Maxzide tablets','Triamterene + HCTZ'),
(388,'Aldactone, Aldactazide','Spironolactone, Spir/HCTZ'),
(389,'Lozol','Indapamide'),
(390,'Thalidone, Hygroton','Chlorthalidone'),
(391,'','Hydrochlorothiazide (aka<br>HCTZ)'),
(394,'Aricept','Donepezil'),
(395,'Exelon, Exelon Patch','Rivastigmine'),
(396,'Fiorinal, Fiorinal with<br>codeine','Butalbital + aspirin +<br>caffeine, available with or<br>without codeine'),
(397,'Fioricet, Fioricet with<br>codeine','Butalbital + acetaminophen<br>+ caffeine (sometimes<br>called B-A-C), available<br>with or without'),
(398,'Buspar','Buspirone'),
(399,'Transderm-Scop','Scopolamine'),
(400,'Remeron','Mirtazapine'),
(401,'Desyrel','Trazodone'),
(403,'Tegretol (XR)','Carbamazepine'),
(404,'Lamictal','Lamotrigine'),
(405,'Keppra','Levetiracetam'),
(406,'Trileptal','Oxcarbazepine'),
(407,'Dilantin Kapseals','Phenytoin Sodium'),
(408,'Depakote (ER)','Divalproex'),
(409,'Phenobarbital','Phenobarbital'),
(410,'Topamax','Topiramate'),
(411,'Neurontin','Gabapentin'),
(412,'Atarax','Hydroxyzine hydrochloride'),
(414,'Relpax','Eletriptan'),
(415,'Maxalt, Maxalt MLT','Rizatriptan'),
(416,'Imitrex','Sumatriptan'),
(417,'Cogentin','Benztropine'),
(418,'Sinemet (CR)','Levodopa/Carbidopa'),
(419,'Mirapex','Pramipexole'),
(420,'Requip','Ropinirole'),
(421,'Zyprexa','Olanzapine'),
(422,'Seroquel (XR)','Quetiapine'),
(423,'Risperdal','Risperidone'),
(424,'Geodon','Ziprasidone'),
(425,'Abilify','Aripiprazole'),
(426,'Antivert','Meclizine'),
(427,'Xanax (XR)','Alprazolam'),
(428,'Klonopin','Clonazepam'),
(429,'Valium','Diazepam'),
(430,'Ativan','Lorazepam'),
(431,'Restoril','Temazepam'),
(432,'Adipex-P','Phentermine'),
(433,'Concerta or Ritalin (ER)<br>or Metadate CD','Methylphenidate'),
(434,'Strattera','Atomoxetine'),
(435,'Adderall (XR)','(Dex)/Amphetamine Mixed<br>salts'),
(436,'Vyvanse','Lisdexamfetamine'),
(437,'Provigil','Modafinil'),
(438,'Focalin (XR)','Dexmethylphenidate'),
(439,'Sonata','Zaleplon'),
(440,'Flexeril','Cyclobenzaprine'),
(441,'Skelaxin','Metaxalone'),
(442,'Soma','Carisoprodol'),
(443,'Duragesic','Fentanyl'),
(444,'MS Contin','Morphine Sulfate'),
(445,'Oxycontin','Oxycodone'),
(446,'Percocet or Roxicet','Oxycodone/APAP'),
(447,'Tylenol with Codeine','Acetaminophen/ Codeine'),
(448,'Tussionex','Hydrocodone /<br>chlorpheniramine Polistirex'),
(449,'Vicoprofen','Hydrocodone/Ibuprofen'),
(450,'Lortab or Vicodin or<br>Lorcet','Hydrocodone/APAP'),
(451,'Lyrica','Pregabalin'),
(452,'Chantix','Varenicline Tartrate'),
(453,'Namenda','Memantine'),
(454,'Voltaren, Cataflam','Enteric Diclofenac sodium,<br>Diclofenac potassium (non<br>enteric coated formulation)'),
(455,'Lodine (XL)','Etodolac'),
(456,'Indocin','Indomethacin'),
(457,'Toradol','Ketorolac Tromethamine'),
(458,'Mobic','Meloxicam'),
(459,'Relafen','Nabumetone'),
(460,'Naprosyn,<br>Anaprox/Aleve','Naproxen and Naproxen<br>sodium'),
(461,'Feldene','Piroxicam'),
(462,'Motrin or Advil','Ibuprofen'),
(463,'Celebrex','Celecoxib'),
(464,'Arthrotec','Diclofenac/Misoprostol'),
(465,'Ultram, Ultram ER','Tramadol'),
(466,'Ultracet','Tramadol + acetaminophen'),
(467,'Tylenol','Acetaminophen'),
(468,'Lunesta','Eszopiclone'),
(469,'Ambien (CR)','Zolpidem'),
(470,'Pristiq','Desvenlafaxine'),
(471,'Cymbalta','Duloxetine'),
(472,'Effexor (XR)','Venlafaxine'),
(473,'Celexa','Citalopram'),
(474,'Lexapro','Escitalopram'),
(475,'Prozac or Sarafem','Fluoxetine'),
(476,'Paxil (CR)','Paroxetine'),
(477,'Zoloft','Sertraline'),
(478,'Lidoderm Patches','Lidocaine'),
(479,'Elavil','Amitriptyline'),
(480,'Tofranil (PM)','Imipramine'),
(481,'Eskalith or Lithobid','Lithium Carbonate'),
(482,'Differin','Adapalene'),
(483,'Benzaclin','Clindamycin/Benzoyl<br>Peroxide'),
(484,'Benzamycin','Erythromycin/Benzoyl<br>Peroxide'),
(485,'Clobex','Clobetasol'),
(486,'Elocon','Mometasone'),
(487,'Kenalog','Triamcinolone'),
(488,'Elidel','Pimecrolimus'),
(489,'Lotrisone','Clotrimazole/Betamethason e Diproprionate'),
(490,'Lidex, Lidex-E, Vanos','Fluocinonide topical'),
(491,'Propecia or Proscar','Finasteride'),
(492,'Accutane or Claravis','isotretinoin'),
(493,'AndroGel','Testosterone'),
(494,'Glucophage (XR),<br>Fortamet','Metformin'),
(495,'Januvia, Janumet (XR)','Sitagliptin, Sit+Metformin'),
(496,'Onglyza','Saxagliptin'),
(497,'Amaryl','Glimepiride'),
(498,'Glucotrol (XL)','Glipizide'),
(499,'Micronase, Glucovance','Glyburide,<br>Glyburide/Metformin'),
(500,'Actos','Pioglitazone'),
(501,'Byetta, Bydureon','Exenatide, Exenatide weekly'),
(502,'Victoza','Liraglutide'),
(503,'Fosamax','Alendronate'),
(504,'Boniva','Ibandronate'),
(505,'Actonel, Atelvia','Risedronate, delayed release enteric coated risedronate'),
(506,'Estratest (HS)','Estrogen/Methyltestosteron e'),
(507,'Combipatch','Estradiol/Norethindrone'),
(508,'Premarin','Conjugated Estrogens'),
(509,'Climara, Estrace','Estradiol'),
(510,'Evista','Raloxifene'),
(511,'Prempro or Premphase','Conjugated Estrogens with medroxyprogesterone'),
(512,'Colcrys','Colchicine'),
(513,'Zyloprim','Allopurinol'),
(514,'Uloric','Febuxostat'),
(515,'Provera','Medroxyprogesterone<br>Acetate'),
(516,'Humulin R','Insulin - regular'),
(517,'Humulin N','Insulin - NPH'),
(518,'Levemir','Insulin Detemir'),
(519,'Lantus','Insulin Glargine'),
(520,'Novolog','Insulin Aspart'),
(521,'Humalog','Insulin Lispro'),
(522,'Apidra','Insulin Glulisine'),
(523,'','Ethinyl Estradiol/<br>Drospirenone'),
(524,'Kariva, Ortho-Cept,<br>Mircette, Desogen or<br>Apri','Ethinyl Estradiol /<br>Desogestrel'),
(525,'Aviane, Alesse','Ethinyl Estradiol /<br>Levonorgestrel'),
(526,'Loestrin FE','Norethindrone/Ethinyl<br>Estradiol,Fe+'),
(527,'TriNessa, Tri-Sprintec','Norgestimate & Ethinyl Estradiol'),
(528,'Ortho Tri-Cyclen (Lo)','Norgestimate/Ethinyl<br>Estradiol'),
(529,'Ortho Evra','Ethinyl Estradiol /<br>Norelgestromin'),
(530,'Novolin 70/30, Humulin<br>70/30','Insulin 70% NPH/ 30 %<br>Regular'),
(531,'Novalog Mix 70/30,<br>Humalog Mix 75/25','Insulin 70% protamine/ 30 % rapid acting'),
(532,'Depo-Provera','Medroxyprogesterone'),
(533,'Deltasone','Prednisone'),
(534,'Medrol','Methylprednisolone'),
(535,'Armour thyroid','Desiccated thyroid'),
(536,'Synthroid or Levoxyl','Levothyroxine'),
(537,'Vivelle-Dot, Estraderm','Estradiol'),
(538,'NuvaRing','Ethinyl Estradiol /<br>Etonogestrel'),
(539,'Vagifem','Estradiol'),
(540,'Bentyl','Dicyclomine'),
(541,'Levsin/Levbid/Levsinex','Hyoscyamine'),
(542,'Imodium','Loperamide'),
(543,'Lomotil','Diphenoxylate/Atropine'),
(544,'Phenergan','Promethazine'),
(545,'Amitiza',''),
(546,'Xenical','Orlistat'),
(547,'Pepcid','Famotidine'),
(548,'Zantac','Ranitidine'),
(549,'Miralax, Glycolax','Polyethylene Glycol'),
(550,'Reglan','Metoclopramide'),
(551,'Nexium','Esomeprazole'),
(552,'Prevacid','Lansoprazole'),
(553,'Prilosec','Omeprazole'),
(554,'Protonix','Pantoprazole'),
(555,'Aciphex','Rabeprazole'),
(556,'Zegerid','Omeprazole/sodium<br>bicarbonate'),
(557,'Avodart','Dutasteride'),
(558,'Flomax','Tamsulosin'),
(559,'Uroxatral','Alfuzosin'),
(560,'Levitra','Vardenafil'),
(561,'Viagra','Sildenafil'),
(562,'Cialis','Tadalafil'),
(563,'Ditropan (XL)','Oxybutynin'),
(564,'Detrol (LA)','Tolterodine'),
(565,'Enablex','Darifenacin'),
(566,'Pyridium','Phenazopyridine'),
(567,'Calcitriol','cholecalciferol'),
(568,'Alphagan P','Brimonidine'),
(569,'Xalatan','Latanaprost'),
(570,'Timoptic (XE)','Timolol'),
(571,'Travatan','Travoprost'),
(572,'Combigan','Brimonidine/Timolol'),
(573,'Pataday or Patanol','Olopatadine'),
(574,'Tobradex','Tobramycin/Dexamethason<br>e'),
(575,'Vigamox','Moxifloxacin'),
(576,'Restasis','Cyclosporine'),
(577,'Cosopt','Dorzolamide/Timolol'),
(578,'Zymar','Gatifloxacin'),
(579,'Lumigan','Bimatoprost'),
(580,'Cortisporin Otic','Neomycin/polymyxin/hydro<br>cortisone'),
(581,'Ciprodex, Cipro HC','Ciprofloxacin/Dexamethaso<br>ne,<br>Ciprofloxacin/Hydrocortison<br>e'),
(582,'Astelin','Azelastine'),
(583,'Rhinocort Aqua','Budesonide Nasal Spray'),
(584,'Flonase','Fluticasone'),
(585,'Nasonex,','Mometasone'),
(586,'Singulair','Montelukast'),
(587,'Proair HFA or Ventolin<br>HFA or Proventil HFA','Albuterol'),
(588,'Xopenex (HFA)','levalbuterol'),
(589,'Pulmicort Respules,<br>Flexhaler','Budesonide Inhalation<br>Suspension'),
(590,'Flovent','Fluticasone'),
(591,'Advair','Fluticasone/Salmeterol'),
(592,'Respimat or Duoneb','Albuterol/Ipratropium'),
(593,'Spiriva HandiHaler','Tiotropium'),
(594,'Atrovent','Ipratropium Bromide'),
(595,'Zyrtec','Cetirizine'),
(596,'Clarinex','Desloratadine'),
(597,'Claritin','Loratidine'),
(598,'Allegra (D)','Fexofenadine (PSE)'),
(599,'Mucinex (D, DM)','Guaifenesin'),
(600,'Cheratussin AC','Guaifenesin & Codeine'),
(601,'Zostavax','herpes zoster vaccine'),
(602,'Gardasil, Cervarix','Human papillomavirus vaccine'),
(603,'Afluria or Fluvirin or Fluzone','influenza virus vaccine'),
(604,'Pneumovax','pneumococcal polysaccharide vaccine'),
(605,'Tdap','Tetanus, Diphtheria,<br>Pertussis Vaccine'),
(606,'Dosage Form<br>Abbreviations<br>XR or XL or ER<br>XE<br>LA<br>SR<br>CR','Extended release<br>Extended effect<br>Long Acting<br>sustained release<br>Controlled release'),
(607,'TTS<br>ODT<br>D<br>PM<br>HS','Transdermal Therapeutic<br>System<br>Orally disintegrating tab<br>Decongestant<br>evening<br>half-s');
/*!40000 ALTER TABLE `Medications` ENABLE KEYS */;
UNLOCK TABLES;
