USE `PrescriptionDatabase`;

LOCK TABLES `Medications` WRITE;
/*!40000 ALTER TABLE `Medications` DISABLE KEYS */;
INSERT INTO `Medications` VALUES
(1,'Suboxone','Buprenorphine/Naloxone'),
(2,'Carisoprodol','Carisoprodol'),
(3,'Celebrex','Celecoxib'),
(4,'Tylenol with Codeine','Codeine'),
(5,'Cyclobenzaprine','Cyclobenzaprine'),
(6,'Diclofenac sodium SR','Diclofenac'),
(7,'Fentanyl transdermal','Fentanyl Transdermal'),
(8,'Hydrocodone/APAP','Hydrocodone'),
(9,'Ibuprofen','Ibuprofen'),
(10,'Indomethacin','Indomethacin'),
(11,'Lidoderm','Lidocaine'),
(12,'Meloxicam','Meloxicam'),
(13,'Methadone HCl non-inj','Methadone'),
(14,'Methocarbamol','Methocarbamol'),
(15,'Morphine sulfate ER','Morphine'),
(16,'Naproxen','Naproxen'),
(17,'OxyContin','Oxycodone'),
(18,'Elmiron','Pentosan'),
(19,'Sumatriptan oral','Sumatriptan'),
(20,'Tramadol','Tramadol'),
(21,'Acyclovir','Acyclovir'),
(22,'Albenza','Albendazole'),
(23,'Amoxicillin','Amoxicillin'),
(24,'Amoxicillin/pot. clav','Amoxicillin/Clavulanate'),
(25,'Reyataz','Atazanavir'),
(26,'Azithromycin','Azithromycin'),
(27,'Cefdinir','Cefdinir'),
(28,'Cefuroxime axetil','Cefuroxime'),
(29,'Cephalexin','Cephalexin'),
(30,'Chlorhexidine gluconate','Chlorhexidine'),
(31,'Ciprofloxacin HCl','Ciprofloxacin Oral'),
(32,'Ciprodex Otic','Ciprofloxacin Otic'),
(33,'Clarithromycin','Clarithromycin'),
(34,'Clindamycin systemic','Clindamycin Systemic'),
(35,'Clindamycin topical','Clindamycin Topical'),
(36,'In Various Combinations','Diphtheria'),
(37,'Doxycycline','Doxycycline'),
(38,'Sustiva','Efavirenz'),
(39,'Truvada','Emtricitabine/Tenofovir'),
(40,'Baraclude','Entecavir'),
(41,'Dificid','Fidaxomicin'),
(42,'Fluconazole','Fluconazole'),
(43,'Zymar','Gatifloxacin Ophthalmic'),
(44,'Pedvax HIB','Haemophilus Influenzae Type B'),
(45,'Havrix','Hepatitis A'),
(46,'Recombivax HB; Engerix-B','Hepatitis B'),
(47,'Gardasil','Human Papillomavirus'),
(48,'Hydroxychloroquine','Hydroxychloroquine'),
(49,'Imiquimod','Imiquimod'),
(50,'Fluzone','Influenza Inactivated'),
(51,'Flumist','Influenza Live'),
(52,'Ketoconazole topical','Ketoconazole Topical'),
(53,'Levaquin','Levofloxacin'),
(54,'Selzentry','Maraviroc'),
(55,'MMR','Measles, Mumps and Rubella'),
(56,'Menactra, Menomune','Meningococcal (Conjugate and Polysaccharide)'),
(57,'Metronidazole tabs','Metronidazole'),
(58,'Minocycline','Minocycline'),
(59,'Avelox','Moxifloxacin'),
(60,'Vigamox','Moxifloxacin Ophthalmic'),
(61,'Mupirocin','Mupirocin'),
(62,'Alinia','Nitazoxanide'),
(63,'Nitrofurantoin mono mcr','Nitrofurantoin'),
(64,'Nystatin systemic','Nystatin Systemic'),
(65,'Nystatin topical','Nystatin Topical'),
(66,'Tamiflu','Oseltamivir'),
(67,'Penicillin VK','Penicillin'),
(68,'In Various Combinations','Pertussis'),
(69,'Prevnar 13, Pneumovax 23','Pneumococcal (Conjugate and Polysaccharide)'),
(70,'IPOL','Polio'),
(71,'Insentress','Raltegravir'),
(72,'RotaTeq','Rotavirus'),
(73,'Terbinafine HCl','Terbinafine'),
(74,'In Various Combinations','Tetanus'),
(75,'Trimethoprim/sulfa','Trimethoprim/Sulfamethoxazole'),
(76,'Valtrex','Valacyclovir'),
(77,'Varivax','Varicella'),
(78,'Zostavax','Zoster'),
(79,'Amlodipine besylate','Amlodipine'),
(80,'Atenolol','Atenolol'),
(81,'Lipitor','Atorvastatin'),
(82,'Benazepril','Benazepril'),
(83,'Zebeta','Bisoprolol'),
(84,'Atacand','Candesartan'),
(85,'Carvedilol','Carvedilol'),
(86,'Hygroton','Chlorthalidone'),
(87,'Clonidine','Clonidine'),
(88,'Plavix','Clopidogrel'),
(89,'Welchol','Colesevelam'),
(90,'Pradaxa','Dabigatran'),
(91,'Digoxin','Digoxin'),
(92,'Diltiazem','Diltiazem'),
(93,'Persantine','Dipyridamole'),
(94,'Doxazosin','Doxazosin'),
(95,'Enalapril','Enalapril'),
(96,'Lovenox','Enoxaparin'),
(97,'Zetia','Ezetimibe'),
(98,'Felodipine ER','Felodipine'),
(99,'Fenofibrate','Fenofibrate'),
(100,'Fosinopril sodium','Fosinopril'),
(101,'Furosemide oral','Furosemide'),
(102,'Gemfibrozil','Gemfibrozil'),
(103,'Hydralazine','Hydralazine'),
(104,'Hydrochlorothiazide','Hydrochlorothiazide'),
(105,'Avapro','Irbesartan'),
(106,'Isosorbide mononitrate','Isosorbide Mononitrate'),
(107,'Labetalol','Labetalol'),
(108,'Lisinopril','Lisinopril'),
(109,'Cozaar','Losartan'),
(110,'Lovastatin','Lovastatin'),
(111,'Metoprolol succinate','Metoprolol'),
(112,'Bystolic','Nebivolol'),
(113,'Niaspan','Niacin'),
(114,'Nifedipine ER','Nifedipine'),
(115,'Nitroglycerin','Nitroglycerin'),
(116,'Benicar','Olmesartan'),
(117,'Lovaza','Omega-3-Ethyl Esters'),
(118,'Effient','Prasugrel'),
(119,'Pravastatin','Pravastatin'),
(120,'Propranolol HCl','Propranolol'),
(121,'Quinapril','Quinapril'),
(122,'Ramipril','Ramipril'),
(123,'Ranexa','Ranolazine'),
(124,'Xarelto','Rivaroxaban'),
(125,'Crestor','Rosuvistatin'),
(126,'Simvastatin','Simvastatin'),
(127,'Spironolactone','Spironolactone'),
(128,'Terazosin','Terazosin'),
(129,'Samsca','Tolvaptan'),
(130,'Triamterene w/HCTZ','Triamterene/Hydrochlorothiazide'),
(131,'Diovan','Valsartan'),
(132,'Verapamil SR','Verapamil'),
(133,'Warfarin','Warfarin'),
(134,'Alendronate','Alendronate'),
(135,'Premarin tabs','Conjugated Estrogen'),
(136,'Cyanocobalamin','Cyanocobalamin'),
(137,'Dexamethasone oral','Dexamethasone'),
(138,'Estradiol oral','Estradiol Oral'),
(139,'Vivelle-DOT','Estradiol Transdermal Patch'),
(140,'Nuvaring','Ethinyl Estradiol/Etonogestrel Ring'),
(141,'Byetta','Exenatide'),
(142,'Folic acid','Folic Acid'),
(143,'Glimepiride','Glimepiride'),
(144,'Glipizide','Glipizide'),
(145,'Boniva','Ibandronate'),
(146,'Humulin N','Insulin'),
(147,'NovoLog','Insulin Aspart'),
(148,'Levemir','Insulin Detemir'),
(149,'Lantus','Insulin Glargine'),
(150,'Humalog','Insulin Lispro'),
(151,'Levothyroxine','Levothyroxine'),
(152,'Tradjenta','Linagliptin'),
(153,'Victoza','Liraglutide'),
(154,'Medroxyprogesterone tab','Medroxyprogesterone Oral'),
(155,'Metformin','Metformin'),
(156,'Methylprednisolone tabs','Methylprednisolone Oral'),
(157,'Oral Contraceptive','Oral Contraceptive - Biphasic'),
(158,'Oral Contraceptive','Oral Contraceptive - Monophasic'),
(159,'Oral Contraceptive','Oral Contraceptive - Triphasic'),
(160,'Actos','Pioglitazone'),
(161,'Klor-Con','Potassium Chloride'),
(162,'SSKI','Potassium Iodide'),
(163,'Prednisolone sd phs oral','Prednisolone Oral'),
(164,'Prednisone oral','Prednisone'),
(165,'Prenatal 1+1','Prenatal 1+1'),
(166,'Prometrium','Progesterone'),
(167,'Evista','Raloxifene'),
(168,'Prandin','Repaglinide'),
(169,'Actonel','Risedronate'),
(170,'Avandia','Rosiglitazone'),
(171,'Onglyza','Saxagliptin'),
(172,'Januvia','Sitagliptin'),
(173,'AndroGel','Testosterone'),
(174,'Thyroid, Armour','Thyroid'),
(175,'Enablex','Darifenacin'),
(176,'Dexilant','Dexlansoprazole'),
(177,'Diphenoxylate w/atropine','Diphenoxylate/Atropine'),
(178,'Nexium','Esomeprazole'),
(179,'Famotidine','Famotidine'),
(180,'Finasteride','Finasteride'),
(181,'Prevacid','Lansoprazole'),
(182,'Amitiza','Lubiprostone'),
(183,'Metoclopramide','Metoclopramide'),
(184,'Omeprazole','Omeprazole'),
(185,'Ondansetron','Ondansetron'),
(186,'Pantoprazole','Pantoprazole'),
(187,'Phenazopyridine HCl','Phenazopyridine'),
(188,'Polyethylene glycol','Polyethylene Glycol'),
(189,'Aciphex','Rabeprazole'),
(190,'Ranitidine HCl','Ranitidine'),
(191,'Flomax','Tamsulosin'),
(192,'Detrol LA','Tolterodine'),
(193,'Differin','Adapalene'),
(194,'Allopurinol','Allopurinol'),
(195,'Arimidex','Anastrozole'),
(196,'Lumigan','Bimatoprost Ophthalmic'),
(197,'Alphagan P','Brimonidine'),
(198,'Clobetasol','Clobetasol'),
(199,'Clotrimazole/betameth.','Clotrimazole/Betamethasone'),
(200,'Colchicine','Colchicine'),
(201,'Restasis','Cyclosporine Ophthalmic'),
(202,'Aranesp','Darbepoetin'),
(203,'Epipen','Epinephrine'),
(204,'Procrit','Epoetin Alfa'),
(205,'Fluocinonide','Fluocinonide'),
(206,'Uloric','Fubuxostat'),
(207,'Hydrocortisone top Rx','Hydrocortisone Topical'),
(208,'Xalatan','Latanoprost'),
(209,'Lotemax','Loteprednol Ophthalmic'),
(210,'Methotrexate','Methotrexate'),
(211,'Viagra','Sildenafil'),
(212,'Tacrolimus','Tacrolimus'),
(213,'Cialis','Tadalafil'),
(214,'Travatan Z','Travoprost'),
(215,'Triamcinolone acet top','Triamcinolone Topical'),
(216,'Levitra','Vardenafil'),
(217,'Tizanidine HCl','Tizanidine'),
(218,'Alprazolam','Alprazolam'),
(219,'Amitriptyline','Amitriptyline'),
(220,'Abilify','Aripiprazole'),
(221,'Strattera','Atomoxetine'),
(222,'Baclofen','Baclofen'),
(223,'Benzonatate','Benzonatate'),
(224,'Benztropine','Benztropine'),
(225,'Bupropion ER','Bupropion'),
(226,'Buspirone HCl','Buspirone'),
(227,'Carbamazepine','Carbamazepine'),
(228,'Carbidopa/levodopa','Carbidopa/Levodopa'),
(229,'Citalopram HBR','Citalopram'),
(230,'Onfi','Clobazam'),
(231,'Clonazepam','Clonazepam'),
(232,'Pristiq','Desvenlafaxine'),
(233,'Focalin XR','Dexmethylphenidate'),
(234,'Diazepam','Diazepam'),
(235,'Dicyclomine HCl','Dicyclomine'),
(236,'Divalproex sodium','Divalproex'),
(237,'Aricept','Donepezil'),
(238,'Doxepin','Doxepin'),
(239,'Cymbalta','Duloxetine'),
(240,'Avodart','Dutasteride'),
(241,'Relpax','Eletriptan'),
(242,'Lexapro','Escitalopram'),
(243,'Lunesta','Eszopiclone'),
(244,'Fluoxetine','Fluoxetine'),
(245,'Gabapentin','Gabapentin'),
(246,'Vimpat','Lacosamide'),
(247,'Lamotrigine','Lamotrigine'),
(248,'Levetiracetam','Levetiracetam'),
(249,'Vyvanse','Lisdexamfetamine'),
(250,'Lithium carbonate','Lithium carbonate'),
(251,'Lorazepam','Lorazepam'),
(252,'Meclizine HCl','Meclizine'),
(253,'Namenda','Memantine'),
(254,'Skelaxin','Metaxalone'),
(255,'Methylphenidate','Methylphenidate'),
(256,'Mirtazapine','Mirtazapine'),
(257,'Provigil','Modafinil'),
(258,'Nortriptyline','Nortriptyline'),
(259,'Zyprexa','Olanzapine'),
(260,'Oxcarbazepine','Oxcarbazepine'),
(261,'Oxybutynin chloride','Oxybutynin'),
(262,'Paroxetine','Paroxetine'),
(263,'Phenobarbital','Phenobarbital'),
(264,'Phentermine','Phentermine'),
(265,'Phenytoin sodium ext','Phenytoin'),
(266,'Mirapex','Pramipexole'),
(267,'Lyrica','Pregabalin'),
(268,'Prochlorperazine maleate','Prochlorperazine'),
(269,'Promethazine tabs','Promethazine'),
(270,'Seroquel','Quetiapine'),
(271,'Risperidone','Risperidone'),
(272,'Ropinirole HCl','Ropinirole'),
(273,'Sertraline','Sertraline'),
(274,'Vesicare','Solifenacin'),
(275,'Temazepam','Temazepam'),
(276,'Topiramate','Topiramate'),
(277,'Trazodone HCl','Trazodone'),
(278,'Chantix','Varenicline'),
(279,'Venlafaxine','Venlafaxine'),
(280,'Viibryd','Vilazodone'),
(281,'Geodon Oral','Ziprasidone'),
(282,'Zolpidem tartrate','Zolpidem'),
(283,'ProAir HFA','Albuterol'),
(284,'Astelin','Azelastine'),
(285,'Pulmicort Respules','Budesonide'),
(286,'Symbicort','Budesonide/Formoterol'),
(287,'Cetirizine','Cetirizine'),
(288,'Fexofenadine','Fexofenadine'),
(289,'Fluticasone nasal','Fluticasone Nasal'),
(290,'Flovent HFA','Fluticasone Oral'),
(291,'Advair Diskus','Fluticasone/Salmeterol'),
(292,'Hydroxyzine','Hydroxyzine'),
(293,'Combivent','Ipratropium/Albuterol'),
(294,'Xopenex HFA','Levalbuterol'),
(295,'Xyzal','Levocetirizine'),
(296,'Nasonex','Mometasone'),
(297,'Singulair','Montelukast'),
(298,'Patanol','Olopatadine'),
(299,'Spiriva','Tiotropium'),
(300,'Nasacort AQ','Triamcinolone Nasal')
